name: example-git-local-repo
base: core22
version: '1.0'
summary: Pulls files from local git repositories
description: Pulls files from local git repositories
grade: stable
confinement: strict

apps:
  example-git-local-repo:
    command: usr/local/bin/hello-world

parts:
  example-git-local-repo:
    plugin: cmake
    source: my/local/repo
    source-type: git
